# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default
  
name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
steps:
- task: CmdLine@2
  inputs:
    script: |
      echo 'Start Build Process'
      $(APIGWDEPLOYTOOLS)/apigateway/posix/bin/projpack --create  --dir=$(Agent.BuildDirectory)"/s" --passphrase-none --name=dev --type=pol --add $(Agent.BuildDirectory)"/s/APIProject11" --projpass-none --add $(Agent.BuildDirectory)"/s/APIProject22" --projpass-none --add $(Agent.BuildDirectory)"/s/commonProject" --projpass-none 
      echo echo 'Package created successfully'
    workingDirectory: '$(HOME)'
  displayName: 'Package build'
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      git add $(Agent.BuildDirectory)/s/.
      git commit -am "Added artificat after git build "$(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
      git push https://x-access-token:$(GitAccessToken)@github.com/prernatiwa/TeamDevelopment.git HEAD:master
  displayName: 'Push build artifact to GIT'