# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default
  
name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
steps:
- task: CmdLine@2
  inputs:
    script: |
      echo 'Start Build Process'
      $(APIGWDEPLOYTOOLS)/apigateway/posix/bin/projpack --create  --dir=$(Agent.BuildDirectory)"/s" --passphrase-none --name=dev --type=pol --add $(Agent.BuildDirectory)"/s/APIProject11" --projpass-none --add $(Agent.BuildDirectory)"/s/APIProject22" --projpass-none --add $(Agent.BuildDirectory)"/s/commonProjectDefault" --projpass-none 
      echo echo 'Package created successfully'
    workingDirectory: '$(HOME)'
  displayName: 'Package build'
- task: CmdLine@2
  inputs:
    script: |
      git config --global user.name "prernatiwa"
      git config --global user.email "prernatiwa@gmail.com"
      git add .
      git commit -m "commit changes from azure build1"
      git push git@github.com:prernatiwa/TeamDevelopment.git HEAD:master
      echo Write your commands here
    workingDirectory: $(Agent.BuildDirectory)/s
  displayName: 'Push build artifact to GIT'